---
version: "3.9"
services:
  fullnode:
    container_name: sui-fullvalidator
    image: mysten/sui-node:stable
    networks:
    - sui-network
    ports:
    - "9000:9000"
    - "9184:9184"
    expose:
    - "9000"
    - "9184"
    volumes:
    - ./fullnode.yaml:/sui/fullnode.yaml:ro
    - ./genesis.blob:/sui/genesis.blob:ro
    - suidb-validator:/sui/suidb:rw
    command: ["/usr/local/bin/sui-node", "--config-path", "fullnode.yaml"]
    restart: unless-stopped
volumes:
  suidb-validator:
networks:
  sui-network:
    external: true

